<?php

namespace Tests\Feature\Unit;

use App\Models\Product;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
//use PHPUnit\Framework\TestCase;

use Tests\TestCase;

class HttpTest extends TestCase
{
    use RefreshDatabase;
    /**
     * A basic feature test example.
     */


    protected $product;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->product =  Product::create([
            'name'  => 'product 1',
            'price'  => 100
        ]);

    }

    public function test_user_can_list_products(): void
    {
        $products = $this->get('/products');

        $products->assertStatus(200)->assertSee('pro');
    }


    public function test_user_show_product_by_id(){
        $product = $this->get('/product/'.$this->product->id);
        $product->assertStatus(200)
                ->assertSee('product 1')
                ->assertSee(100);
    }
}
